#!/bin/bash
# Fix nginx module loading issues before nginx starts.
#
# Problem: In production ARM64 containers, nginx-extras .so modules
# (Lua, NDK, Perl, GeoIP) may NOT be installed, causing nginx to fail.
#
# This script:
# 1. Removes /etc/nginx/modules-enabled/ symlinks for missing .so files
# 2. If Lua modules are missing, replaces nginx-code-server.conf with
#    a Lua-free version (code-server IDE loses auto-start feature, app unaffected)

echo "[fix-nginx] Starting nginx module compatibility check..."

# Get nginx modules path (e.g., /usr/lib/nginx/modules)
MODULES_PATH=$(nginx -V 2>&1 | tr ' ' '\n' | grep "modules-path" | cut -d= -f2)
[ -z "$MODULES_PATH" ] && MODULES_PATH="/usr/lib/nginx/modules"
echo "[fix-nginx] Modules path: $MODULES_PATH"

# Helper: resolve relative module path to absolute
resolve_module() {
    local path="$1"
    path=$(echo "$path" | tr -d '"' | tr -d "'" | tr -d ';')
    if [[ "$path" = /* ]]; then
        echo "$path"
    else
        echo "$MODULES_PATH/$(basename "$path")"
    fi
}

# Check if Lua module is available
LUA_MISSING=false
if [ ! -f "$MODULES_PATH/ngx_http_lua_module.so" ] || [ ! -f "$MODULES_PATH/ndk_http_module.so" ]; then
    LUA_MISSING=true
    echo "[fix-nginx] Lua/NDK modules NOT found - will use Lua-free nginx configs"
fi

# -------------------------------------------------------------------
# STEP 1: Fix /etc/nginx/modules-enabled/ symlinks
# -------------------------------------------------------------------
REMOVED=0
for conf in /etc/nginx/modules-enabled/*.conf; do
    [ -f "$conf" ] || continue
    mod_line=$(grep "load_module" "$conf" 2>/dev/null | head -1)
    [ -z "$mod_line" ] && continue
    rel_path=$(echo "$mod_line" | awk '{print $2}' | tr -d '";')
    [ -z "$rel_path" ] && continue
    abs_path=$(resolve_module "$rel_path")

    if [ ! -f "$abs_path" ]; then
        echo "[fix-nginx] Removing broken symlink: $(basename $conf) (missing: $abs_path)"
        rm -f "$conf"
        REMOVED=$((REMOVED + 1))
    fi
done
echo "[fix-nginx] Removed $REMOVED broken module symlink(s)"

# -------------------------------------------------------------------
# STEP 2: If Lua is missing, replace nginx-code-server.conf with 
#         a simple Lua-free proxy config
# -------------------------------------------------------------------
CODE_CONF="/etc/nginx/nginx-code-server.conf"
if [ "$LUA_MISSING" = true ] && [ -f "$CODE_CONF" ]; then
    echo "[fix-nginx] Replacing nginx-code-server.conf with Lua-free version..."
    cat > "$CODE_CONF" << 'NGINX_CONF'
# Lua-free nginx config for code-server proxy
# (Auto-generated by fix_nginx_modules.sh when Lua modules are unavailable)
user root;

events {
    worker_connections 1024;
}

http {
    access_log /var/log/nginx/code-access.log;
    error_log /var/log/nginx/code-error.log;

    upstream code-server {
        server 127.0.0.1:8080;
    }

    server {
        listen 1111;
        server_name _;

        location / {
            proxy_pass http://code-server;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 10s;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
            proxy_intercept_errors on;
            error_page 502 503 504 = @unavailable;
        }

        location @unavailable {
            default_type text/html;
            return 503 '<html><body><h2>IDE starting...</h2><script>setTimeout(()=>location.reload(),5000)</script></body></html>';
        }
    }
}
NGINX_CONF
    echo "[fix-nginx] nginx-code-server.conf replaced with Lua-free version"
fi

# -------------------------------------------------------------------
# STEP 3: Verify nginx configs
# -------------------------------------------------------------------
if nginx -t -c /etc/nginx/nginx.conf 2>/dev/null; then
    echo "[fix-nginx] nginx.conf: OK"
else
    echo "[fix-nginx] WARNING: nginx.conf still invalid"
fi

if [ -f "$CODE_CONF" ]; then
    if nginx -t -c "$CODE_CONF" 2>/dev/null; then
        echo "[fix-nginx] nginx-code-server.conf: OK"
    else
        echo "[fix-nginx] WARNING: nginx-code-server.conf still invalid"
    fi
fi

echo "[fix-nginx] Done."
exit 0
