services:
  - type: web
    name: scormify-api-bootstrap
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./backend/Dockerfile.bootstrap
    dockerContext: ./backend
    healthCheckPath: /health
    autoDeployTrigger: off
