services:
  - type: web
    name: scormify-api
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: off
